### ISSUE TITLE
[Feature Request] More Features

### ISSUE THREAD

**Issue by EvanHsieh0415** [xiaoliziawa/keyboardJS#1]
# Changes

## Merge Namespaces
- [ ] `KEYS.xxx` -> `KeyboardJS.KEYS.xxx`
  example: `KeyboardJS.KEYS.F3`
- [ ] `Keyboard.pressed` / `Keyboard.released` -> `KeyboardJS.pressed` / `KeyboardJS.released`

# News

## Combinations Keys
- [ ] `KeyboardJS.KEYS.combination(KeyboardJS.KEYS.KEY[])`
  example: `KeyboardJS.KEYS.combination([KeyboardJS.KEYS.SHIFT, KeyboardJS.KEYS.A])`

## Get Custom Keybind
- [ ] `KeyboardJS.KEYBIND.custom(keybind_name: str)`

## Keybind Register
- [ ] `"keyboardjs:keybind"`
  ```js
  StartupEvents.registry("keyboardjs:keybind", (event) => {
    event
      .create("kubejs:foo")
      .displayName("Custom Key: Foo")
      .defaultKey(KeyboardJS.KEYS.combination([KeyboardJS.KEYS.SHIFT, KeyboardJS.KEYS.A]))
      .group(() => "kubejs:group");

    event
      .create("kubejs:bar")
      .defaultKey(KeyboardJS.KEYS.F3)
      .group(() => "custom:group");
  });
  ```
- [ ] `"keyboardjs:keybind_group"`
  ```js
  StartupEvents.registry("keyboardjs:keybind_group", (event) => {
    event.create("custom:group").displayName("Custom Group");
  });
  ```

**Comment by xiaoliziawa** [comment]
Great idea, try adding it in future updates

**Comment by xiaoliziawa** [comment]
I gave up on this fucking project.
